### ISSUE TITLE
Keep a deny.toml.example in the repository

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#108]
**Is your feature request related to a problem? Please describe.**
`cargo deny init` now initializes a full `deny.toml` file including a lot of comments. This is good for getting started, but for a long-term config file I prefer having a denser config file that only has my deviations from the defaults (and with comments that are specific to why my project needs them, rather than generic ones about the config file format).

**Describe the solution you'd like**
At the same time, having the denser README than before is also an improvement. Generating the full, defaults-included deny.toml and keeping it in the repo would provide a useful reference, making it easy to cross-check my project's config against the upstream default and documentation (this also makes it available in a way that gets versioned along with the rest of the project).

**Comment by Jake-Shadle** [comment]
Yah, that make sense! Would you want it to make 2 copies, or just create the example one, and then an empty deny.toml?

**Comment by djc** [comment]
I was actually talking about keeping it in *this* repository.

**Comment by djc** [comment]
Also because, in the current setup, there's no easy reference (if I want to keep a dense config) of what is actually allowed in the config file.

**Comment by Jake-Shadle** [comment]
Hmm ok. Maybe it would make sense to just have anchor links for each section in the template and take out the verbose comments in favor of the detailed descriptions already in the documentation?

**Comment by djc** [comment]
That wouldn't work as well for me particularly. I really like having (a) one document where I can review the entire possible contents of the file and (b) a dense config file which only has my project-specific stuff.

**Comment by Jake-Shadle** [comment]
Would something like this work?

```ini
[[targets]]
triple = "a-target-triple"
features = ["a-target-feature"]

[advisories]
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/RustSec/advisory-db"
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = ["RUSTSEC-0000-0000"]

[bans]
multiple-versions = "warn"
highlight = "all"

[[bans.deny]]
name = "a-crate-name"
version = "*"

[[bans.allow]]
name = "a-crate-name"
version = "*"

[[bans.skip]]
name = "a-crate-name"
version = "*"

[[bans.skip-tree]]
name = "a-crate-name"
version = "*"
depth = 0

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "warn"
confidence-threshold = 0.8
deny = ["an-spdx-id"]
allow = ["an-spdx-id"]

[[licenses.clarify]]
name = "a-crate-name"
version = "*"
expression = "an-spdx-expression"

[[licenses.clarify.license-files]]
path = "relative/license/path"
hash = 3735928559

[[licenses.exceptions]]
name = "a-crate-name"
version = "*"
allow = ["an-spdx-id"]

[licenses.private]
ignore = false
registries = ["https://a-registry-url"]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["a-git-url"]
```

**Comment by djc** [comment]
It would be nice, although having the fully documented version would be nicer still.

**Comment by Jake-Shadle** [comment]
Ok, I think I am just really confused by what you actually want, could you provide a small sample that I can extrapolate from?

**Comment by djc** [comment]
Basically the output from `cargo deny init`, but kept in this repository as a reference instead of in my project's repositories.

**Comment by djc** [comment]
(BTW, I heard your podcast interview over the weekend, very nice to get some context.)

**Comment by Jake-Shadle** [comment]
`cargo deny init` prints out the copy of [resources/template.toml](https://github.com/EmbarkStudios/cargo-deny/blob/master/resources/template.toml) stored in the binary when it is compiled, is that file not sufficient already?

**Comment by djc** [comment]
Ah, I wasn't aware of that. I think that probably covers this then! I guess this would be easier to find if it was linked from the README and/or lived in the root as `deny.toml.example`.

**Comment by Jake-Shadle** [comment]
Yah, I guess it is kind of hidden at the moment, I'll put it in the root to make it easier to find, sorry for the confusion!

**Comment by djc** [comment]
No problem at all, thanks for your patience!
