### ISSUE TITLE
Target limitation doesn't seem to work for duplicate detection

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#111]
**Describe the bug**
I have this duplicate dependency:

```rust
warning: found 2 duplicate entries for crate 'nom'

    ┌── /Users/djc/src/valuex/Cargo.lock:83:1 ───
    │
 83 │ ╭ nom 4.2.3 registry+https://github.com/rust-lang/crates.io-index
 84 │ │ nom 5.1.0 registry+https://github.com/rust-lang/crates.io-index
    │ ╰───────────────────────────────────────────────────────────────^ lock entries
    │

    = nom v4.2.3
      └── weedle v0.10.0
          └── wasm-bindgen-webidl v0.2.58
              └── (build) web-sys v0.3.35
                  └── ring v0.16.9
                      └── backend v0.1.0

    = nom v5.1.0
      └── askama_derive v0.9.0
          └── askama v0.9.0
              └── backend v0.1.0
```

However, I also have this in my config:

```rust
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]
```

I would expect this configuration to silence this warning, since the ring -> web-sys dependency is guarded by `[target.'cfg(all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown", target_env = ""))'.dependencies]`.

**Comment by Jake-Shadle** [comment]
Just to make sure, this is using a version built from `master`? Can you use `-L debug` to change the log level, it will show all the crates that get completely filtered out due to cfg filtering at the beginning.

**Comment by djc** [comment]
No, this is using the released version from crates.io.

**Comment by djc** [comment]
It doesn't seem to be filtering anything out. Was that implemented after the last release?

**Comment by Jake-Shadle** [comment]
Yes, I was planning on cutting a new release today, sorry for the confusion.

**Comment by djc** [comment]
No problem, that's fine!
