### ISSUE TITLE
`cargo deny list` doesn't seem to honor the `targets` config

### ISSUE THREAD

**Issue by luser** [EmbarkStudios/cargo-deny#117]
I added a `targets` section to our `deny.toml`, and then ran `cargo deny list` to get a list of licenses in use and populated the `licenses.allow` section with all of the listed licenses. When I then ran `cargo deny check licenses` it produced warnings telling me that some of the licenses in the `allow` list were not in use.

Here's some snippets of output from running the commands locally:
```
$ cargo deny list
<...>
Apache-2.0 WITH LLVM-exception (1): wasi@0.7.0
<...>
$ cargo deny check licenses
warning: license was not encountered

    ┌── <...>/deny.toml:26:5 ───
    │
 26 │     "Apache-2.0 WITH LLVM-exception",
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no crate used this license
```

**Expected behavior**
Crates that are not built using the set of listed targets should not show up in `cargo deny list` output.

**Comment by Jake-Shadle** [comment]
Yes, right now the configuration is only taken into account for the check subcommand. I think if you pass the `-t, --target` option list will respect that. Should include the targets config in the list though, thanks!

**Comment by luser** [comment]
For the record: yes, explicitly listing `--target=...` for each target in our `targets` list does produce the expected output.
