### ISSUE TITLE
Confusing warning when x11-dl changed license

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#119]
`x11-dl` just changed from CC0-1.0 license in v2.18.4 to MIT in v2.18.5, which is great. We generally do not allow CC0-1.0 licenses so we didn't have it in our license allow list but instead had an explicit exception for it like this:

```toml
exceptions = [
    { allow = ["CC0-1.0"], name = "x11-dl" },
]
```

But then when we upgraded to the latest `x11-dl` that used MIT license (which is in our allow list) I got the following quite confusing warning:

![image](https://user-images.githubusercontent.com/1262692/73134080-49dd3e00-4032-11ea-892c-3e62ac12e8f0.png)

MIT is in the allow list so this sounded quite strange. Removing the above exception line for `x11-dl` 's old CC0-1.0 license fixed this warning though.

I would have expected when updating the crate to get a warning instead of an unused license exception for `x11-dl` with CC0-1.0.

**Comment by Jake-Shadle** [comment]
The allow list for exceptions is the only one used because they tend to be unique single licenses, but would be easy to have them be in addition to the global ones and then give a warning if the additional ones then weren't actually used

**Comment by repi** [comment]
Ah so the exceptions actually overrules the allow list for a crate? Yeah that is rather cryptic

**Comment by Jake-Shadle** [comment]
See #135 for the underlying issue description.
