### ISSUE TITLE
Windows path failure in 0.6.3

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#131]
Upgraded from 0.6.2 to 0.6.3 on my Windows box and got the following error in our repo:

![image](https://user-images.githubusercontent.com/1262692/74064692-7fe7ce00-49f3-11ea-8e42-8bbffcc2536a.png)

Some path / canonicalization regression in 0.6.3?

**Comment by Jake-Shadle** [comment]
Ahh, oops, I don't have a test for that, I'll probably just take off path canonicalization altogether.

**Comment by repi** [comment]
Thanks!

**Comment by repi** [comment]
Can confirm it fixed the problem!
