### ISSUE TITLE
Cargo deny doesn't exit after run

### ISSUE THREAD

**Issue by patriksvensson** [EmbarkStudios/cargo-deny#141]
Thanks for an awesome tool!

**Describe the bug**
After running `cargo deny check -d` (or `cargo deny check`), the application does not exit after printing diagnostics. I have to press `Ctrl+C` to abort the run. Same thing happens on both Linux (Ubuntu and archlinux) and Windows.

I've tried adding the `-L trace` to see if it's doing something, but there is nothing in the output that indicates that it does.

**To Reproduce**
I have no idea how to reproduce it at the moment. Will try to create a minimal reproducible example, but thought I would log it here first (in case I'm holding it wrong in an obvious way).

**Expected behavior**
Cargo-deny should exit after it's done.

**Device:**
 - OS: *Windows 10*
 - Version: *1903 build 18362.657*

**Additional context**
* I'm using `cargo-deny` version 0.6.4.
* The `deny.toml` can be found here: https://github.com/spectresystems/duck/commit/a83d26637a8aca318779bb0e6947579f563d8058#diff-d5e8db5f728f1472868ffbfc4146fec3

**Comment by Jake-Shadle** [comment]
Hmm weird. I think I might have seen this once before, but haven't in a while. Might be a race somewhere since we spawn several worker threads in the check command.

**Comment by patriksvensson** [comment]
@Jake-Shadle This doesn't seem to be a bug after all. If I leave `cargo deny check` for about 5-10 minutes, it will finish, and the subsequent run finishes in a couple of seconds after that as intended.

Clearing Cargo's registry cache/index/src will make the check run slowly again, which makes sense.

Perhaps we could add some logging to make it apparent that cargo-deny is doing something and haven't hung?

**Comment by Jake-Shadle** [comment]
Ahh ok, so I take it you don't have a lock file? Either way that's an insanely long time doing a fetch, as that's what I am assuming is causing the stall, as fetching is done during lock file generation by default.

**Comment by patriksvensson** [comment]
@Jake-Shadle Hmm, yes, I have a lock file. My app is a binary I distribute so it’s committed to the repo. 

Perhaps creating a memory dump from the time it hangs could provide more insight in what the problem is. I’ll take a closer look at it tomorrow.

**Comment by Jake-Shadle** [comment]
How long does running `cargo metadata` take? That is where I would expect it to take time, but only if it needs to fetch crate sources that aren't already local. The only other network operation that occurs is the fetching of the advisory database, which is logged (try `-L debug` before `check` to see more info on that part).

**Comment by Jake-Shadle** [comment]
Closing for now as I have heard of no other issues with this.
