### ISSUE TITLE
Provide a prebuilt binary for CI.

### ISSUE THREAD

**Issue by najamelan** [EmbarkStudios/cargo-deny#171]
**Is your feature request related to a problem? Please describe.**
Running `cargo-install` in CI is long and wastes precious resources.

**Describe the solution you'd like**
Provide a prebuilt binary in releases (similar to wasm-pack) that can be installed in CI without building from source. As cargo deny doesn't do
any platform specific stuff, just crate analysis, it's probably fine to just provide a linux binary.

**Describe alternatives you've considered**
An alternative is to use caching in CI to be able to re-use the compiled binary, but one still has to manage upgrades and rebuilt every time the cache needs clearing.

**Additional context**
The [wasm-pack install instructions](https://rustwasm.github.io/wasm-pack/installer/) as an example.

**Comment by repi** [comment]
This we already have: https://github.com/EmbarkStudios/cargo-deny/releases

And we also have a GitHub Action that uses the pre-built exe, that one can use (if one uses GitHub actions): https://github.com/embarkstudios/cargo-deny-action

**Comment by najamelan** [comment]
Sorry about this and thanks for replying so quickly. I didn't realize the tar.gz files where binary releases. Now testing it out on travis. I think it is possible to polish it a bit by adding a little shell script that will automatically get the latest version, so people don't need to update their ci files all the time. Akin to the wasm-pack installer, and mention that in the readme. Other than that, I think it does work.

**Comment by Jake-Shadle** [comment]
We supply a separate [Github action](https://github.com/EmbarkStudios/cargo-deny-action) that downloads and runs the latest. We don't use anything other than github actions for our public repositories so we don't plan on adding utilities ourselves since we wouldn't be able to effectively maintain them.
