### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by frol** [EmbarkStudios/cargo-deny#175]
**Is your feature request related to a problem? Please describe.**

I created AUR package for Arch Linux: https://aur.archlinux.org/packages/cargo-deny/

The installation instructions for Arch Linux users:

```
yay -S cargo-deny
```

**Describe the solution you'd like**

I suggest adding this (as installation instructions or just a mention of the link) to the README

**Comment by Jake-Shadle** [comment]
Neat! My one concern would be a new release being published without a corresponding update to the AUR package, and people filing issues against the version in AUR that were fixed/addressed in later versions, but that's just a hypothetical for now.

**Comment by frol** [comment]
I subscribed for the releases on GitHub, and anyway, Arch Linux users  are used to flagging the version on the repository (there is such feature). Yet, feel free to ping me if there is an issue related to the package
