### ISSUE TITLE
Fold in security advisories

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#18]
Currently, we're using a separate tool, [cargo-audit](https://github.com/RustSec/cargo-audit), to check security advisories, would be simpler to just use the [advisory-db](https://github.com/RustSec/advisory-db) directly as an additional check instead of having to download/install/run a separate tool.

**Comment by repi** [comment]
This would be a good intermediate step and simplify things! 

I do think @mitsuhiko idea of having the audits and ban graph folded into the Cargo dependency resolver would be even more powerful and easier later though:

https://twitter.com/mitsuhiko/status/1162386888931651584
https://github.com/rust-lang/cargo/issues/7193

But that we can track as a separate thing and if that does get in evolve cargo-deny to drive what crates to allow/enable.
