### ISSUE TITLE
Clarification of the license doesn't work

### ISSUE THREAD

**Issue by Veetaha** [EmbarkStudios/cargo-deny#181]
Version: `cargo-deny v0.6.6`

**Describe the bug**
`stream-vbyte` crate uses some license not included in SPDX, that's why I added a clarification
to say that it is `Unlicense` (in fact the particular license doesn't matter, `MIT` doesn't work either), however `cargo deny` reports that it has no license at all.
<details>
<summary>cargo deny check output</summary>

```
~/junk/cargo-deny-bug-report (master) $ cargo deny check
error: stream-vbyte 0.3.2 (registry+https://github.com/rust-lang/crates.io-index) is unlicensed

   ┌── stream-vbyte 0.3.2 (registry+https://github.com/rust-lang/crates.io-index):2:9 ───
   │
 2 │ name = "stream-vbyte"
   │         ^^^^^^^^^^^^ a valid license expression could not be retrieved for the crate
   ·
 4 │ license = ""
   │            - license expression was not specified
   ·
 6 │     { path = "LICENSE.txt", hash = 0x508d93ea, score = 0.31 },
   │                                                        ---- low confidence in the license text
   │
   = stream-vbyte v0.3.2
     └── cargo-deny-bug-report v0.1.0

2020-04-30 12:23:01 [ERROR] encountered 1 errors
```

</details>

Also, I cannot just explicitly `{ allow = "NONE", name = "stream-vbyte" }` or smth to allow an unlicensed dependency in `licenses.exceptions`, this means I need to set `licenses.unlicensed = "warn"`, which is bad for me...

**To Reproduce**
1. Clone [this repo](https://github.com/Veetaha/cargo-deny-bug-report)

**Expected behavior**
No error report, the check should be successful.

**Device:**
 - OS: `Ubuntu 18.04 LTS`

**Additional context**
I love your tool!

**Comment by Jake-Shadle** [comment]
Ahh, that's a shame, I've never encountered this particular corner case before, thanks for the report, I will look at it when able!

**Comment by Veetaha** [comment]
I am also not able to run `cargo deny check -g outdir`, it hangs indefinitely and populates all my RAM. Unfortunately, the project where I run this is private and contains a huge dependency tree (thanks to your tool we identified 25 items that are duplicated in 2 or 3 versions). I'll try to localize this once I have an opportunity!

**Comment by Jake-Shadle** [comment]
If possible, try running `cargo fetch` before running `cargo deny`, cargo deny internally uses `cargo metadata` to retrieve all of the crate metadata, which requires crates be downloaded locally, which can take a long time on a clean machine, if you do the fetch beforehand you should see if it is actually a hang problem in cargo deny or not.

**Comment by Veetaha** [comment]
Nah, it doesn't save the day :D. All I see is
<details>
<summary>Output</summary>

```
$ cargo deny check -g outdir
warning: found 2 duplicate entries for crate 'ansi_term'

   ┌── /home/veetaha/my_project/Cargo.lock:3:1 ───
   │
 3 │ ╭ ansi_term 0.11.0 registry+https://github.com/rust-lang/crates.io-index
 4 │ │ ansi_term 0.12.1 registry+https://github.com/rust-lang/crates.io-index
   │ ╰──────────────────────────────────────────────────────────────────────^ lock entries
   │
   = ansi_term v0.11.0
     ├─<tree_here>

warning: stream-vbyte 0.3.2 (registry+https://github.com/rust-lang/crates.io-index) is unlicensed

   ┌── stream-vbyte 0.3.2 (registry+https://github.com/rust-lang/crates.io-index):2:9 ───
   │
 2 │ name = "stream-vbyte"
   │         ^^^^^^^^^^^^ a valid license expression could not be retrieved for the crate
   ·
 4 │ license = ""
   │            - license expression was not specified
   ·
 6 │     { path = "LICENSE.txt", hash = 0x508d93ea, score = 0.31 },
   │                                                        ---- low confidence in the license text
   │
   = stream-vbyte v0.3.2
     └<tree_here>
```
</details>
And nothing more, after that, the process is hung... Maybe this is somehow connected with `stream-vbyte` problem?

**Comment by Veetaha** [comment]
We get into an infinite loop when there are cyclic dependencies in the graph...

**Comment by Jake-Shadle** [comment]
Ahh thanks!

**Comment by Veetaha** [comment]
@Jake-Shadle sorry for false-positive, but I've just found the reason. I actually misspelled the license file name in the clarification clause.
So I had
```yml
license-files = [
    { path = "LICENCE.txt", hash = 0x508d93ea }
]
```
Where it must be LICEN**S**E.txt...
But it would be much helpful if there was an error message indicating that the license file specified explicitly in the config was not found.

**Comment by Jake-Shadle** [comment]
Ahh ok, yah that's not a good experience, sorry about that. I'll close this issue and open a new one about providing a good error message when the license file isn't found.
