### ISSUE TITLE
Add "default feature" check

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#206]
Many crates that have features tend to take a "batteries included" approach and put many/all of those features into the `default` feature set, meaning that projects can implicitly fetch and build crates with functionality they don't use nor want.

Cargo/crates.io/docs.rs don't really have a standard way of showing what features a crate even has, much less which ones are in the default set, and thus often requires manual inspection of the Cargo.toml for the crate, in addition to the fact that any version can add new features to the `default` set, or add the `default` feature itself if it wasn't in a previous version.

In light of this, it would be nice to have a check specifically for the existence of the `default` feature so that users can easily know if they are implicitly pulling in dependencies so that they can modify their Cargo.toml to disable default features and specifically opt-in to the features they actually want.

This also has implications for transitive dependencies, as most crates tend to just use the default features for their dependencies, instead of reexporting optional features under their own feature flag so that the feature is propagated up the dependency hierarchy until a root crate can actually make a decision on if that particular feature should be enabled or not.

**Comment by repi** [comment]
On a related note, would also want to be able to deny or require a specific feature of a crate. (esp. the deny). 

For example: make sure `reqwest` is not used with its `blocking` feature.

**Comment by Jake-Shadle** [comment]
Or the `cookie` feature. ;)

**Comment by repi** [comment]
Ran into a case today with the `juniper` crate that unfortunately has quite a lot of default features in it ([link](https://github.com/graphql-rust/juniper/blob/ed6b257e5871b1e125943a82e1f0346e8fd08693/juniper/Cargo.toml#L30)) that then brought in `bson` and `linked-hash-map` crates as additional dependencies that we didn't use.

This future check would have caught that and warned that we were using a crate without `default-features = false`.

**Comment by Jake-Shadle** [comment]
#226 is a more comprehensive issue that is kind of a superset of this issue, but I'll keep both open for now as I think a solution would still need to take default into account.
