### ISSUE TITLE
Optional dependency that is not enabled still considered as part of the license checks

### ISSUE THREAD

**Issue by sdroege** [EmbarkStudios/cargo-deny#216]
**To Reproduce**
1. Go to https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/tree/master/gstreamer
2. Check the `Cargo.toml` and notice the `gstreamer-rs-lgpl-docs` crate as an optional dependency hidden behind a feature flag
3. Try running `cargo deny check` in the whole cargo workspace after removing the `licenses.exceptions` from `deny.toml`
4. Notice that `cargo deny` complains about there being a copyleft license involved, and that LGPL-2.0 is not a allowed license

**Expected behavior**

No problematic license would be found as the feature flag is not enabled by anything in the repository.

**Comment by Jake-Shadle** [comment]
This is because we gather metadata with all-features enabled, I will add support for the normal cargo feature-related options so that you can specify which ones you want enabled when checking, as long as you specify a specific crate's manifest path and not a workspace.

**Comment by sdroege** [comment]
Thanks!
