### ISSUE TITLE
Consider how to handle license exceptions

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#22]
In #21 I ran into the `wasi` crate license: `Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT`. This has an exception that is curently handled as a separate license `LLVM-exception`.

Think it may be better to handle any `WITH` part with the licenses as a single long full license instead, so `Apache-2.0 WITH LLVM-exception` in this case and require users to add that exact license _with_ the exception to the allow list.

**Comment by Jake-Shadle** [comment]
Resolved by #29
