### ISSUE TITLE
Add check for wildcard crate versions

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#221]
Ran into a couple of our crates that were using (major) wildcard dependency versions, which can much more easily break as will automatically get updated to any latest version when doing `cargo update` (when having a lock file) or when building (when not having a lockfile).

So for most of our own repos I would want to disallow wildcard versions in crate dependencies:

E.g. this syntax in Cargo.toml for crates:

```toml
[dependencies]
anyhow = "*"
glam = "*"
```

More info about Cargo.toml wildcard dependencies: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#wildcard-requirements

crates.io doesn't allow crates to be published with it so it should be less of a concern for external dependencies, though other registries could allow it so scanning transitively would make sense still.

**Comment by yamafaktory** [comment]
Hi and thank you for this awesome project!

I was interested in trying to figure out a fix for this issue but then quickly noticed that `cargo-deny` uses `cargo_metadata` under the hood. Thus, if I get it correctly, the plugin relies on the output of `cargo metadata` which resolves the versions out of the box https://github.com/EmbarkStudios/cargo-deny/blob/main/src/lib.rs#L197. Currently, it doesn't seem to grab the original `"*"` wildcard as it is already mapped internally to a `Semver` version (the latest available one).

To reproduce it, I did a quick debug within the project:

```toml
[dependencies]
# ...
# Change rustsec version to be a wildcard on purpose:
rustsec = "*"
```
```sh
cargo run check
[src/lib.rs:195] pkg.clone() = Package {
    name: "rustsec",
    version: Version {
        major: 0,
        minor: 21,
        patch: 0,
        pre: [],
        build: [],
    },
...
```
Maybe another approach would be to additionally read from `cargo.toml`, parse it with https://crates.io/crates/toml and check the current - non-resolved - version? Not sure though if this a correct and efficient approach...

**Comment by khodzha** [comment]
this is what i arrived at
https://github.com/EmbarkStudios/cargo-deny/pull/227

**Comment by Veetaha** [comment]
Sounds nice, @Jake-Shadle should we close this one?

**Comment by Jake-Shadle** [comment]
Right oops, added in 0.7.2, thanks again @khodzha!
