### ISSUE TITLE
Disallow deprecated/unmaintained crates

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#23]
Randomly ran into and saw that we were using the [`quickersort`](https://crates.io/crates/quickersort) crate in our main repo and saw that it is marked on crates.io / `Cargo.toml` as "maintenance: deprecated". So I removed our usage of it and added it to our crate deny list

It would be great to add support for detecting deprecated / unmaintained crates and have a setting in `cargo-deny` to disallow them by default, potentially with an allow list for which one one wants to opt using anyway. Instead of manually having to add all of them which one typically does in hindsight.

Likely can't detect all of them but in the `quickersort` case, and hopefully for a bunch of other cases, the crate was marked in `Cargo.toml` with the following we could use:

```toml
[badges]
maintenance = { status = "deprecated" }
```

Today there was a highly related discussion also on RustSec and cargo-audit of marking deprecated crates in the RustSec security advisory: https://github.com/RustSec/advisory-db/issues/134 
Having a proper database for it that doesn't require the author / repo-owner to mark their own crates as deprecated/unmaintained would be even better. But this likely would take a bit longer as a community effort to get going so we could start with the badge detection in `cargo-deny` and see how it goes and then adapt? 

We've talked before also about having `cargo-deny` also directly read from the RustSec security advisories instead of using `cargo-audit` as a separate step, to have more control of it.

**Comment by Jake-Shadle** [comment]
This PR contains the code for interacting with the new unmaintained information available in the advisory db. https://github.com/RustSec/rustsec-crate/commit/1698651afb49999cbb55e6f7c8770ed671774b07
