### ISSUE TITLE
Option to allow specific unlicensed crates

### ISSUE THREAD

**Issue by stanislav-tkach** [EmbarkStudios/cargo-deny#250]
**Is your feature request related to a problem? Please describe.**
As far as I can see, there is no way to allow only some specific crates without license. I don't want to allow all unlicensed crates, but I would like to make some exceptions.

More specifically, I'm using [AWS lambda Rust runtime](https://github.com/awslabs/aws-lambda-rust-runtime). This repository contains the license file, but it is located outside of the crate directory. I suppose `[[licenses.clarify]]` section is of no use in that case.

**Describe the solution you'd like**
I would like to have a skip/ignore option for the `[licenses]` section where the crates excluded from the license check can be listed.

**Describe alternatives you've considered**
One more option is to make `license-files` in the `[[licenses.clarify]]` section optional.

**Comment by Jake-Shadle** [comment]
In the future this would be addressed by something like #121 where anyone could submit curations to clearlydefined.io for any crate published on crates.io, but looking at that repository it's fairly clear that they have the Apache-2.0 license for all of the crates, so submitting a PR that either puts the LICENSE in the published crate, or to just specify `license = "Apache-2.0"` for `lambda` and `lambda-attributes` as `lambda-http` already specifies it.

**Comment by stanislav-tkach** [comment]
I have already submitted a pull request (https://github.com/awslabs/aws-lambda-rust-runtime/pull/251), but unfortunately it hasn't been merged for 20 days. That leaves me in the situation where I have to disable license checking and do it manually.

I agree that usually it is better to choose a different crate, but sometimes it isn't possible. In such situation it would be useful to specify the license manually (or disable the check for that crate) for a specific version or git commit.

It would be nice if clearlydefined.io solved all these issues, my only concern is to have a quick solution.

**Comment by Jake-Shadle** [comment]
Ahh ok, that's a shame, I will see about providing a patch tomorrow for this.

**Comment by Jake-Shadle** [comment]
Correction, no patch is needed, just specify `license-files = []` in the clarification, along with the name and expression as with the normal clarification.

**Comment by stanislav-tkach** [comment]
Could you please give a little bit more instructions on how to use `license-files`? It is stated in the comment that path is a crate relative and in my case the license file is located outside of the crate directory. Am I missing something?

**Comment by Jake-Shadle** [comment]
Just leave the array empty, if you don't give it any files to check it doesn't do anything.

**Comment by stanislav-tkach** [comment]
Thanks! This idea hasn't crossed my mind.
