### ISSUE TITLE
Can't determine license for adler 1.0.4

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#27]
A patch update of `adler32` was released yesterday, 1.0.4. Which we updated to with `cargo update` and after that `cargo-deny` failed:

```sh
 Sep 19 23:33:56.472 ERRO unable to determine license with high confidence, src: text=/Users/johan/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.0.4/LICENSE,hash=0x1e225da6, score: 0.6267943, crate: adler32@1.0.4
 Sep 19 23:33:56.472 ERRO encountered 1 license errors
```

So looks like 1.0.4 changed the license to `Zlib` in https://github.com/remram44/adler32-rs/commit/413c6138b43838f96a0c620fcfc9ceab9cc84dc0 which `cargo-deny` for some reason isn't able to detect.

Will downgrade us for now to 1.0.3 but we should look into this asap.

**Comment by Jake-Shadle** [comment]
Hehe, I saw that change yesterday and was actually wondering if cargo-deny would handle it correctly, guess I know now!
