### ISSUE TITLE
Disallow specific versions of crates?

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#28]
After testing the new Cargo nightly [`-Z timings`](https://internals.rust-lang.org/t/exploring-crate-graph-build-times-with-cargo-build-ztimings/10975/5) output I quickly saw that the old `winapi 0.2` crate was a big bottleneck when compiling for Windows. So want to get rid of it and upgrade or remote all of our dependencies that use it (directly or transitively).

We are still a ways of from being able to get rid of the dependency but once we do I would like to add it `winapi 0.2` to our bans deny list so we don't get it back. 

Want this:

```toml
[bans]
multiple_versions = "deny"
deny = [
    { name = "openssl" },
    { name = "app_dirs" },       # abandoned, use app_dirs2 instead

    { name = "winapi", version = "<0.3" }
]
```

But this doesn't fail on our usage of `winapi 0.2` (wrong) nor `winapi 0.3` (correct), Is a version parameter supported here?

**Comment by Jake-Shadle** [comment]
Hmm, that should work, but now that I think about it, dunno if I ever tested specific versions for bans before so maybe it is just broken. Will take a look next week.

**Comment by repi** [comment]
Thanks, and yes not urgent but would be good to be able to do.

**Comment by Jake-Shadle** [comment]
Actually, this works, with the current version, you just need to also delete the skip entry for `winapi =0.2.8` as skips are processed first.

**Comment by repi** [comment]
Cool thx
