### ISSUE TITLE
Crash when running license check with Rust 1.47.0

### ISSUE THREAD

**Issue by cberner** [EmbarkStudios/cargo-deny#286]
**Describe the bug**
`cargo deny check licenses` fails with Rust 1.47.0

**To Reproduce**
1. `git clone https://github.com/fleetfs/fleetfs`
2. `cd fleetfs && git checkout 80cc4212e79a5e38dff8c8e2b118bcc8eee3fa09`
3. `rustup override set 1.47.0`
4. `cargo deny check licenses`

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: 21', /home/cberner/.cargo/registry/src/github.com-1ecc6299db9ec823/krates-0.2.0/src/builder.rs:543:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
No error, as observed when using `rustup override set 1.46.0`

**Device:**
 - OS: Ubuntu 20.04

**Comment by Jake-Shadle** [comment]
Thanks for the report! This is resolved, I just need to cut a release of cargo-deny (hopefully today?), but if you want to work around this in the meantime, you can use the `rev = <commit-sha>` specifier instead of the `branch = <branch_name>` specifier.
