### ISSUE TITLE
Support running without a typical rust installation

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#295]
#54 was closed by #243, but unfortunately that was apparently just the miniboss, as cargo internally calls `rustc` when gathering metadata

eg, `rustc -vV` and `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` are called, and while `rustc -vV` is easy to fake that's...the only one.

The original intention of #54 was to be able to run cargo-deny in minimal container environments, so opening this as a new issue since at least cargo is out of the way, but rustc might be a lot harder.

**Comment by luser** [comment]
FYI the first invocation comes from [`Rustc::new`](https://github.com/rust-lang/cargo/blob/f12d72e11b8643b4851a50325d77af962931fe98/src/cargo/util/rustc.rs#L34) which gets called via [`Config::load_global_rustc`](https://github.com/rust-lang/cargo/blob/c369b8c8d85a90579ab2f7fd0332701a9e9dc65b/src/cargo/util/config/mod.rs#L334). That codepath does use a cache in `target/.rustc_info.json`, so you could write a dummy file out there to force it to avoid that. It gets called in [`RustcTargetData::new`](https://github.com/rust-lang/cargo/blob/7f44ba46d3de2e72da2b43ff42524db36326c700/src/cargo/core/compiler/build_context/target_info.rs#L6720, which is called from [`build_resolve_graph `](https://github.com/rust-lang/cargo/blob/8ff53f6424f32a2f5d71c3b668ba30099fe92570/src/cargo/ops/cargo_output_metadata.rs#L115), which is called from `output_metadata`.

The second invocation is in [`TargetInfo::new`](https://github.com/rust-lang/cargo/blob/7f44ba46d3de2e72da2b43ff42524db36326c700/src/cargo/core/compiler/build_context/target_info.rs#L135), which gets called one or more times for every target specified in [`RustcTargetData::new`](https://github.com/rust-lang/cargo/blob/7f44ba46d3de2e72da2b43ff42524db36326c700/src/cargo/core/compiler/build_context/target_info.rs#L6720). This seems a bit excessive, maybe cargo could be changed to load this information on-demand?

**Comment by Jake-Shadle** [comment]
Ahh nice, might take a look at that for a workaround!
