### ISSUE TITLE
Add subcommand to compile list of licenses as JSON

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#30]
Similarly to [license-hound](https://github.com/maghoff/cargo-license-hound) it would be good to have a sub-command that compiles a JSON object containing all of the crates/sources and under which license(s) they are being licensed with according to the user's config.

This JSON output could then be transformed into whatever the user likes through others tools, but the intended use case would be for something like a static HTML page similarly to what Firefox does in `about:license`

**Comment by artrs-prog** [comment]
I'm interested to take a look.

**Comment by Jake-Shadle** [comment]
Cool!

I need to land #29 first, but the idea after that would be...

1. Perform a license gather like the `check` subcommand already does, using the user supplied configuration
2. For each license requirement that the configuration says the user accepts, add that crate to a list keyed by the license id.
3. For each unique SPDX license id (note that Apache-2.0 WITH LLVM-exception would be different from Apache-2.0), get the full license text. There are a couple of ways you could do this
  * Just add reqwest (using rustls) and grab them from https://github.com/spdx/license-list-data
  * Shell out to git and clone the same repo, grab the texts then nuke the repo
  * We already store match data for license text in the askalono store which is a part of the binary, but not the full license text. You could update `spdx_cache.bin.gz` to include the full license text by cloning askalono, and doing `cargo run -- cache load-spdx --store datasets/spdx-json && cp askalono-cache.bin.gz ../cargo-deny/spdx_cache.bin.gz` and then grabbing the license text by decompressing and deserializing the LicenseEntry::text entry manually.
4. Serialize each unique license as an object with the full text and an array of objects with the crate name, version, and link to the repository and/or crates.io

**Comment by evanjs** [comment]
This sounds like it could be really helpful, and I can't really find any crates right now that get me this close to generating a NOTICE/Acknowledgements/EULA file, save e.g. `cargo-license --json`, which still requires some work after that, AFAIK.

**Comment by Jake-Shadle** [comment]
Moving this to a separate utility -> https://github.com/EmbarkStudios/cargo-about
