### ISSUE TITLE
Allow --exclude to be specified in deny.toml

### ISSUE THREAD

**Issue by luser** [EmbarkStudios/cargo-deny#312]
Our Rust codebase has crates for Android and iOS support and a third one we call `shared-mock` which is a pure-Rust platform for testing the non-platform-specific parts of our codebase. Unfortunately that crate pulls in a lot of dependencies so it can do native windowing, which results in us dealing with warnings and errors from `cargo deny` that aren't really important for us to address. I found that I can use `cargo deny --exclude=shared-mock check` to avoid this problem, but that requires us to always pass that argument. That means that anyone else running the tool needs to know to pass that argument, which is unfortunate.

I'd like it if we could specify the `--exclude=` option in `deny.toml`, so that anyone running `cargo deny check` on our codebase will get the same results.

**Comment by Jake-Shadle** [comment]
Yup, seems reasonable. 👍
