### ISSUE TITLE
Add a reference link for copyleft licenses

### ISSUE THREAD

**Issue by luser** [EmbarkStudios/cargo-deny#323]
[The docs for the `licenses.copyleft` config](https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html#the-copyleft-field-optional) link to Wikipedia for the definition of "copyleft", but that's not very helpful in terms of knowing what licenses it applies to. In attempting to simplify our current list of allowed licenses I changed our config to:

```toml
[licenses]
allow-osi-fsf-free = "either"
unlicensed = "deny"
copyleft = "deny"
default = "deny"
```

only to find that MPL-2.0 (which is the license used by `cbindgen`) is considered copyleft. From looking around I understand that you're using the SPDX license list data, but I couldn't easily find a list of licenses from there that are considered copyleft. If there's a useful link you could provide in these docs that would be helpful!

(As an aside, I can understand why MPL-2.0 is considered copyleft, but given that it only requires copyleft-style handling on a per-file basis it's not viral like the GPL/LGPL are.)

**Comment by Jake-Shadle** [comment]
I believe I pulled the list from the gnu license page that goes through the various popular oss licenses and explains why each one is/isn't copy left, but that might be buried in a code comment.
