### ISSUE TITLE
Allowing the licenses without SPDX identifier

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#325]
I'm trying to get the intel-mkl-src crate past cargo deny. This crate has a license-file but there doesn't appear to be an SPDX identifier for it as far as I can see. I found something in the book about referencing "user-defined licenses" using `LicenseId-id`, but I have not been able to find anything about how to define one. Am I missing some docs, or is this scenario not yet supported?

**Comment by Jake-Shadle** [comment]
Oh weird, I thought I had linked the relevant section from the [SPDX spec](https://spdx.github.io/spdx-spec/6-other-licensing-information-detected/#61-license-identifier) but that looks like it's not the case. You should be able to write `LicenseRef-` + _identifier_ wherever you would write a regular SPDX short identifier.

This reminded me I had a similar issue in https://github.com/EmbarkStudios/cargo-deny/issues/51, so should definitely improve the docs in this area.

**Comment by djc** [comment]
The docs you added in #326 make it clearer how to use custom identifiers, but it's not yet clear to me how to **define** one. Can I use a `clarify` object to attach a custom identifier to some particular license file (hash)?

**Comment by Jake-Shadle** [comment]
Oh yes, exactly, you'd be assigning the custom identifier to that crate and then using it in the allow or exception list, I'll add that to the docs. Our normal use case for custom identifiers was for the local crates in the workspace so in that case we just set it in the regular cargo.toml license field.
