### ISSUE TITLE
Ignore sec-advisories for some crate until a given date

### ISSUE THREAD

**Issue by bnjbvr** [EmbarkStudios/cargo-deny#345]
Bytecode Alliance folks have ran into an interesting use case: a low-urgency sec-advisory that is fine to ignore for some time, but that should be re-reviewed some time later: https://github.com/bytecodealliance/wasmtime/pull/2881. To not forget about it, it'd be nice that `cargo-deny` can "ping back" after a given date, while ignoring the issue until the given date. Is that something that would make sense to add in `cargo-deny`?

(There's the question of which time zone should be applied to such a date, but any would work, really; I don't expect that being a day early or late in this kind of situation would be dramatic.)

**Comment by bnjbvr** [comment]
> but don't think I want to go back to that failing (essentially random) builds either.

That's a good point. Maybe that's a different feature request, but it'd be nice if there was a way to run the sec-advisories checks only with a certain `cargo deny` runtime flag; then users could use Github period jobs (cron-like) to just run the sec-advisories checks, separate from the rest of the Cargo deny checks. This way, the sec-advisories checks wouldn't happen in random builds, but in separate instances.

**Comment by Jake-Shadle** [comment]
This is already supported, `cargo deny check` by default will run all checks, but you can specify which checks to run, eg `cargo deny --all-features check advisories`
