### ISSUE TITLE
Allow suppressing `license was not encountered` warning

### ISSUE THREAD

**Issue by soenkeliebau** [EmbarkStudios/cargo-deny#352]
**Is your feature request related to a problem? Please describe.**
We are using cargo-deny from CI in a number of internal repositories and have a list of licenses which we consider acceptable that should be applied to all repositories.

Since not all repositories have dependencies covering the entire list of allowed licenses we consistently get the below warning in some repositories:

```
warning[L006]: license was not encountered
   ┌─ /github/workspace/deny.toml:14:5
   │
14 │     "BSD-3-Clause",
   │     ^^^^^^^^^^^^^^ unmatched license allowance
```

**Describe the solution you'd like**
Ideally we'd like to be able to add a config setting to our deny.toml which says that we do not care about unmatched licenses from the whitelist, which would then suppress that warning.

**Describe alternatives you've considered**
We've considered two alternatives:

1. Keep a separate list of licenses per repository and remove unused ones
2. Live with the warning

We went with 2 for now, as option 1 creates unneeded overhead and the warning doesn't fail the CI job.

**Comment by lfrancke** [comment]
Thank you @thomcc! This is useful.

**Comment by soenkeliebau** [comment]
I indeed, thanks a lot!
