### ISSUE TITLE
Copyleft "warn" will allow a license

### ISSUE THREAD

**Issue by lfrancke** [EmbarkStudios/cargo-deny#354]
**Describe the bug**

When `copyleft` is set to `warn` (which is the default) all the precedence checks after point 3 in this list https://embarkstudios.github.io/cargo-deny/checks/licenses/index.html#evaluation-precedence will not be considered anymore because `warn` is treated as `allow`:

https://github.com/EmbarkStudios/cargo-deny/blob/main/src/licenses/mod.rs#L127-L138

```rust
                    match cfg.copyleft {
                        LintLevel::Allow => {
                            allow!(IsCopyleft);
                        }
                        LintLevel::Warn => {
                            warnings += 1;
                            allow!(IsCopyleft);
                        }
                        LintLevel::Deny => {
                            deny!(IsCopyleft);
                        }
                    }
```

This basically resembles this config:
```
[licenses]

copyleft = "warn"
default = "deny"
```

**Expected behavior**
I would expect `warn` to behave like `neither` from `allow-osi-fsf-free` with an additional warning message: Fall through to the next check.

In theory I'd be happy to provide a PR but I haven't looked at the code yet on how to emit a warning _and_ continue.

**Device:**
 - Version 0.9.1

**Comment by reivilibre** [comment]
I find it odd how, with the default config from `cargo deny init`, I get failures for permissive licences like `MIT` but only `warning[accepted]` for copyleft licences like `MPL-2.0`.

I would expect the default opinion for the tool to not take a stance on copyleft and let you specify individual licences to approve like normal.
