### ISSUE TITLE
Unable to clarify the license of a crate

### ISSUE THREAD

**Issue by daladim** [EmbarkStudios/cargo-deny#373]
# Describe the bug
I cannot succeed in clarifying the license of a crate for which cargo-deny is unable to detect that this is a MIT license.

# To reproduce
This is a minimal reproducer:

**Cargo.toml**
```
[package]
name = "deny"
version = "0.1.0"
edition = "2018"

[dependencies]
console-subscriber = { git = "https://github.com/tokio-rs/console.git", rev = "31704326f2e8665a7f062ceca84bf8d843007017" }
```

**main.rs**: anything will do

**deny.toml**
These are  only the default values (generated by `cargo deny init`) unless commented otherwise
```
targets = []
exclude = [
   # This does not remove the errors about "console-api = 0.1.0 is unlicensed"
   "https://github.com/tokio-rs/console.git#console-api:0.1.0"
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    # I un-commented these licenses to whitelist most of the deps
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    # This would not work: "Invalid license, empty expression"
    # { allow = [""], name = "console-subscriber", version = "*" },
]

[[licenses.clarify]]
# Still rejected by `cargo deny check licenses`: "unable to locate specified license file"
name = "console-api"
version = "*"
expression = "MIT"
license-files = [
   # It looks like cargo-deny cannot find any file
   # I tried with many combinations of "LICENSE", "Cargo.toml", and "console-api/", "../", etc., which no luck
   { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = [""]
gitlab = [""]
bitbucket = [""]
```

# What is the problem

This comes from an actual project, where I'd like to use the `console-api` and `console-subscriber` crates. These crates are MIT licensed, but cargo-deny is unable to detect it.

## What I tried
1. I tried to clarify the license.
    However, this fails (see the above `deny.toml`) because cargo-deny is unable to find the `LICENSE` file, for a reason I cannot explain (is this related to this dependency being pulled form github instead of crates.io?)
1. As a workaround, I tried to add these crates in the `licenses.exceptions`
    However, this fails (see the above `deny.toml`) because cargo-deny enforces the `licenses.exceptions.allow` to have non-empty strings
1. I tried to add the package ID of these crates to the root-level `exlcude` array, with no visible impact

I am not sure what I could do to resolve my issue

**Comment by daladim** [comment]
Thanks for your quick investigation. I was actually about to leave a "maybe that's due to the LICENSE file being from a workspace instead of a crate" :)

So, you're right in saying that the problem comes from the upstream crates which do not contain a suitable LICENSE file (and I'll file a MR as you suggested).
However, these items still puzzle me (is this due to a bug in cargo-deny? or to a misconfiguration of mine?):
* the fact that adding the crate to `exclude` has no effect
* the fact that even cheating by "clarifiying" using a file that actually exists in the crate (e.g. `Cargo.toml`) fails
* what if I'm using a crate that is published, that has no license, and that the author ignores MR? In that case, we're stuck with unlicensed crates, how could I explicitly accept a few of them in deny.toml? (instead of forking them just to add a license)

In my case, this is preventing my automatic builds to run (because our pipeline requires cargo-deny to pass), and I wished there was a way to tell cargo-deny to ignore these crates, however weird they are (that would be a quicker temporary fix :-p )

**Comment by Jake-Shadle** [comment]
- `exclude` does work, if you didn't observe it having an affect you most likely had an incorrect pkg id spec so the crate wasn't filtered. Using `-L debug` will show crates being filtered out, here is what the output looks like if you just specify `exclude = ["console-subscriber"]`

```
2021-11-08 18:50:32 [DEBUG] filtered console-api 0.1.0 git+https://github.com/tokio-rs/console.git?rev=31704326f2e8665a7f062ceca84bf8d843007017#31704326f2e8665a7f062ceca84bf8d843007017
2021-11-08 18:50:32 [DEBUG] filtered console-subscriber 0.1.0 git+https://github.com/tokio-rs/console.git?rev=31704326f2e8665a7f062ceca84bf8d843007017#31704326f2e8665a7f062ceca84bf8d843007017
```

- Like I said in the previous comment, allowing licenses to be found above the crate root would only work for path and git dependencies, not published ones, which are a vast majority of the ecosystem. I'll eventually add support for fetching files from the source repository a crate is packaged from the same as [cargo-about](https://embarkstudios.github.io/cargo-about/cli/generate/config.html#the-clarify-field-optional) but I haven't had time to work on that yet.
- crates.io requires that crate manifests specify either a `license` or `license-file` to be published which is why this particular case is problematic, none of the crates are published so the maintainers have not been forced to specify one of them

**Comment by daladim** [comment]
Thanks for your reply.
It turns out `exclude` works like a charm...provided that I use the latest cargo-deny binary (I was still using v0.8.0 that I installed a while ago).
