### ISSUE TITLE
cargo deny check for packages

### ISSUE THREAD

**Issue by dzmitry-lahoda** [EmbarkStudios/cargo-deny#400]
**Is your feature request related to a problem? Please describe.**
I want to run Ban on specific package instead of whole workspace.

**Describe the solution you'd like**
I have big solution. Want to start deny several version from small steps. And put these checks into CI. Untik whole solution covered.

**Describe alternatives you've considered**
Generate and modify workspace per subset. Dirty hack

**Additional context**
```
cargo deny check --manifest-path /foo/bar/Cargo.toml Ban
```

**Comment by Jake-Shadle** [comment]
You can already do this, I think you just just have the `--manifest-path` argument in the wrong position.

`cargo deny --manifest-path /foo/bar/Cargo.toml check bans`

**Comment by dzmitry-lahoda** [comment]
yes, i have put it into check. thanks.
