### ISSUE TITLE
Cannot use SSH to fetch advisory DB

### ISSUE THREAD

**Issue by jbg** [EmbarkStudios/cargo-deny#412]
**Describe the bug**
If an SSH Git URL is provided for the advisory DB, cargo-deny exits with "error: advisory database url is not https".

**To Reproduce**
1. Set something like `db-urls = ["ssh://git@git.yourcompany.com/yourcompany/rustsec-advisory-db.git"]` in `deny.toml`
2. Run `cargo deny`
3. See error

**Expected behavior**
The advisory DB was cloned over SSH.

**Additional context**
The check is here: https://github.com/EmbarkStudios/cargo-deny/blob/main/src/advisories/cfg.rs#L131

The `rustsec` crate seems to delegate cloning Git repositories to the `git2` crate so I see no reason why the SSH clone would not work if this check was removed.

**Comment by jbg** [comment]
With the check removed, I'm able to clone an advisory DB over SSH without any problem. I opened #426 to remove the check.

**Comment by Jake-Shadle** [comment]
Sorry, had closed this issue before I did #422 but had vaguely remembered it since I included `ssh` https://github.com/EmbarkStudios/cargo-deny/pull/422/files#diff-ec77dabc8549946f0798d5f19ef476febb6891063bda87f22a42223d10543937R219 as a valid scheme.
