### ISSUE TITLE
Separate license check for [dev-dependencies] vs [dependencies]

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/cargo-deny#413]
Sometimes, it might be interesting to use libraries with release-incompatible licenses in `[dev-dependencies]`. One example would be `dssim`, which is licensed under AGPL, and can be useful for comparing graphical output to a reference image while tolerating minor visually-invisible differences. In this case, its license doesn't need to be considered for the final binary release since neither the code nor any of its output will be included in it.

In deny.toml, the interface for this could be to simply have an additional `allow-dev` section. Like below:

```
[licenses]
...
allow = ["MIT", "Apache-2.0", "zlib"]
dev-allow = ["GPL", "AGPL"]
```

`dev-allow` would implicitly include everything from `allow`, since I can't really imagine a case where a library would not be OK to use for local tests, but OK in a final binary.

**Comment by kazuk** [comment]
I wish to add `build-allow` for `[build-dependencies]`
