### ISSUE TITLE
unable to find reference 'refs/heads/main'

### ISSUE THREAD

**Issue by aminya** [EmbarkStudios/cargo-deny#439]
**Describe the bug**
I am trying to run cargo-deny, but it fails with a strange error:

```
> cargo-deny check --hide-inclusion-graph --show-stats

2022-07-27 09:46:30 [ERROR] unable to find reference 'refs/heads/main'

```

I have used the same repository on Windows without any issues, but I am running it under Fedora now.

The issue is fixed if I append `--disable-fetch`! 

**To Reproduce**
1. Run `cargo-deny check --hide-inclusion-graph --show-stats `

**Expected behavior**
It should not fail

**Screenshots**
N/A

**Device:**
 - OS: Fedora 36
 - Browser: Edge
 - Version 0.12.1

**Additional context**

**Comment by Jake-Shadle** [comment]
I'm assuming this was a temporary network error, this code is not platform specific and I can't repro it.
