### ISSUE TITLE
Local unpublished crate is "yanked"

### ISSUE THREAD

**Issue by cemoktra** [EmbarkStudios/cargo-deny#441]
**Describe the bug**
We have a local crate with `publish = false` set. This crate has a naming conflict with a crate publicly available on crates.io. Now the version of our local crate matches a yanked version on crates.io. 

**To Reproduce**
Create an unpublished local crate with a naming conflict on crates.io. Set the version to a yanked version of the public crate. Depend on this crate. Fail

**Expected behavior**
A local crate with `publish = false` should not be checked against crates.io

**Comment by Jake-Shadle** [comment]
This was actually already fixed in https://github.com/EmbarkStudios/cargo-deny/pull/430 I just haven't cut a release yet.
