### ISSUE TITLE
Add Ability To Ignore Path Wildcard Dependencies

### ISSUE THREAD

**Issue by AldaronLau** [EmbarkStudios/cargo-deny#448]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to use `wildcards = "deny"`, but only for non-path-based dependencies.

**Describe the solution you'd like**
Add a config option to specify whether wildcard checks apply to repository-local dependencies, preferably the default is no.

**Describe alternatives you've considered**
Change behavior to not apply wildcard checks to dependencies specified by path.

**Additional context**
None

**Comment by alice-i-cecile** [comment]
Running into this in https://github.com/DioxusLabs/taffy/pull/258.
