### ISSUE TITLE
cargo-deny crashes on crates using custom defined license-file's 

### ISSUE THREAD

**Issue by foresterre** [EmbarkStudios/cargo-deny#45]
**Describe the bug**
`cargo-deny` mixes absolute and relative paths for `license-file` license file paths and crashes on custom^ relative paths specified by crate authors in the Cargo.toml. 

^custom meaning: a path which is not located in the crates' root and does not start with "LICENSE". 

**To Reproduce**
1. Create a new rust crate, for example `cargo new mycrate`
2. Add a (text) file which name does __not__ start with LICENSE (or isn't located at the root of the crate).
3. Update the `Cargo.toml` to include this file as `license-file`*  (akin to [this](https://github.com/foresterre/cargo-deny-debug-fail-cases/blob/dbb26210dc648e8679547a4abf62b153552df657/fail0/Cargo.toml#L6) example)
4. Include a `deny.toml` [example](https://github.com/foresterre/cargo-deny-debug-fail-cases/blob/dbb26210dc648e8679547a4abf62b153552df657/fail0/deny.toml)
5. Run `cargo deny check`

*note that the path should be relative; if one includes an absolute path as value for the `license-file` key, the program runs fine.

**Expected behavior**

An analysis result of the included custom license text. (i.e. not a crash)

**Actual behavior**

`cargo-deny` crashes (see screenshots)

**Screenshots**

Original discovery based on:
![Screenshot from 2019-11-22 01-57-19](https://user-images.githubusercontent.com/5955761/69389164-252bb980-0cc3-11ea-9090-a9cf797e1018.png)

Running both the latest master and the latest crates.io version against a [minimal example](https://github.com/foresterre/cargo-deny-debug-fail-cases/tree/dbb26210dc648e8679547a4abf62b153552df657/fail0):
![cargo-deny-fail0](https://user-images.githubusercontent.com/5955761/69389188-35dc2f80-0cc3-11ea-9f9f-ce29efa3ad26.png)

**Device:**
 - OS: Linux/Ubuntu 19.10
 - Browser: N/A
 - Version: 19.10

**Additional context**
-

**Comment by Jake-Shadle** [comment]
Fixed by #46
