### ISSUE TITLE
Cargo-deny failed to install on FreeBSD 13.1-RELEASE-p1

### ISSUE THREAD

**Issue by JacobsonLantern** [EmbarkStudios/cargo-deny#450]
I'm trying to install cargo deny using `cargo install --locked cargo-deny`. But it throws this error:

> pvmadm@dev:~/dev/msv-auth $ cargo install --locked cargo-deny
>     Updating crates.io index
>   Installing cargo-deny v0.12.2
>   Downloaded quote v1.0.20
>   Downloaded serde v1.0.140
>   Downloaded serde_derive v1.0.140
>   Downloaded rustsec v0.26.0
>   Downloaded semver v1.0.12
>   Downloaded thiserror v1.0.31
>   Downloaded clap_derive v3.2.15
>   Downloaded os_str_bytes v6.2.0
>   Downloaded ryu v1.0.10
>   Downloaded clap v3.2.16
>   Downloaded thiserror-impl v1.0.31
>   Downloaded time v0.3.12
>   Downloaded unicode-ident v1.0.2
>   Downloaded libc v0.2.126
>   Downloaded serde_json v1.0.82
>   Downloaded syn v1.0.98
>   Downloaded anyhow v1.0.59
>   Downloaded combine v4.6.4
>   Downloaded fs-err v2.7.0
>   Downloaded proc-macro2 v1.0.42
>   Downloaded paste v1.0.7
>   Downloaded camino v1.0.9
>   Downloaded once_cell v1.13.0
>   Downloaded either v1.7.0
>   Downloaded crates-index v0.18.8
>   Downloaded os_info v3.4.0
>   Downloaded itoa v1.0.2
>   Downloaded serde_ignored v0.1.4
>   Downloaded cargo-util v0.2.0
>   Downloaded 29 crates (2.1 MB) in 26.27s
>    Compiling autocfg v1.1.0
>    Compiling libc v0.2.126
>    Compiling proc-macro2 v1.0.42
>    Compiling unicode-ident v1.0.2
>    Compiling quote v1.0.20
>    Compiling syn v1.0.98
>    Compiling serde_derive v1.0.140
>    Compiling serde v1.0.140
>    Compiling cfg-if v1.0.0
>    Compiling pkg-config v0.3.25
>    Compiling version_check v0.9.4
>    Compiling once_cell v1.13.0
>    Compiling crossbeam-utils v0.8.11
>    Compiling tinyvec_macros v0.1.0
>    Compiling matches v0.1.9
>    Compiling scopeguard v1.1.0
>    Compiling semver v1.0.12
>    Compiling serde_json v1.0.82
>    Compiling itoa v1.0.2
>    Compiling rayon-core v1.9.3
>    Compiling memchr v2.5.0
>    Compiling log v0.4.17
>    Compiling percent-encoding v2.1.0
>    Compiling unicode-bidi v0.3.8
>    Compiling ryu v1.0.10
>    Compiling target-lexicon v0.12.4
>    Compiling camino v1.0.9
>    Compiling zstd-safe v5.0.2+zstd.1.5.2
>    Compiling hashbrown v0.12.3
>    Compiling termcolor v1.1.3
>    Compiling paste v1.0.7
>    Compiling platforms v3.0.1
>    Compiling static_assertions v1.1.0
>    Compiling byteorder v1.4.3
>    Compiling anyhow v1.0.59
>    Compiling crossbeam-queue v0.3.6
>    Compiling radium v0.7.0
>    Compiling smallvec v1.9.0
>    Compiling bitflags v1.3.2
>    Compiling either v1.7.0
>    Compiling regex-syntax v0.6.27
>    Compiling heck v0.4.0
>    Compiling unicode-width v0.1.9
>    Compiling tap v1.0.1
>    Compiling fixedbitset v0.4.2
>    Compiling os_str_bytes v6.2.0
>    Compiling openssl-probe v0.1.5
>    Compiling home v0.5.3
>    Compiling textwrap v0.15.0
>    Compiling rustc-hash v1.1.0
>    Compiling lazy_static v1.4.0
>    Compiling strsim v0.10.0
>    Compiling funty v2.0.0
>    Compiling time-macros v0.2.4
>    Compiling fs-err v2.7.0
>    Compiling ansi_term v0.12.1
>    Compiling memoffset v0.6.5
>    Compiling crossbeam-epoch v0.9.10
>    Compiling indexmap v1.9.1
>    Compiling num-traits v0.2.15
>    Compiling rayon v1.5.3
>    Compiling tinyvec v1.6.0
>    Compiling proc-macro-error-attr v1.0.4
>    Compiling proc-macro-error v1.0.4
>    Compiling smartstring v1.0.1
>    Compiling form_urlencoded v1.0.1
>    Compiling twox-hash v1.6.3
>    Compiling spdx v0.8.1
>    Compiling codespan-reporting v0.11.1
>    Compiling wyz v0.5.0
>    Compiling clap_lex v0.2.4
>    Compiling codespan v0.11.1
>    Compiling unicode-normalization v0.1.21
>    Compiling jobserver v0.1.24
>    Compiling num_cpus v1.13.1
>    Compiling num_threads v0.1.6
>    Compiling atty v0.2.14
>    Compiling crossbeam-channel v0.5.6
>    Compiling fern v0.6.1
>    Compiling aho-corasick v0.7.18
>    Compiling cfg-expr v0.10.3
>    Compiling bitvec v1.0.1
>    Compiling cc v1.0.73
>    Compiling idna v0.2.3
>    Compiling time v0.3.12
>    Compiling petgraph v0.6.2
>    Compiling rmp v0.8.11
>    Compiling regex v1.6.0
>    Compiling openssl-src v111.22.0+1.1.1q
>    Compiling libz-sys v1.1.8
>    Compiling libssh2-sys v0.2.23
>    Compiling zstd-sys v2.0.1+zstd.1.5.2
>    Compiling libgit2-sys v0.13.4+1.4.2
>    Compiling crossbeam-deque v0.8.2
>    Compiling openssl-sys v0.9.75
>    Compiling crossbeam v0.8.2
> error: failed to run custom build command for `openssl-sys v0.9.75`
> 
> Caused by:
>   process didn't exit successfully: `/tmp/cargo-installqvnEQ5/release/build/openssl-sys-a68d12fed98b67e8/build-script-main` (exit status: 101)
>   --- stdout
>   cargo:rustc-cfg=const_fn
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_NO_VENDOR
>   X86_64_UNKNOWN_FREEBSD_OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
>   OPENSSL_NO_VENDOR unset
>   CC_x86_64-unknown-freebsd = None
>   CC_x86_64_unknown_freebsd = None
>   HOST_CC = None
>   CC = None
>   CFLAGS_x86_64-unknown-freebsd = None
>   CFLAGS_x86_64_unknown_freebsd = None
>   HOST_CFLAGS = None
>   CFLAGS = None
>   CRATE_CC_NO_DEFAULTS = None
>   DEBUG = Some("false")
>   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
>   running "perl" "./Configure" "--prefix=/tmp/cargo-installqvnEQ5/release/build/openssl-sys-a4e2e488e57c07ad/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "BSD-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
>   Configuring OpenSSL version 1.1.1q (0x1010111fL) for BSD-x86_64
>   Using os-specific seed configuration
>   Creating configdata.pm
>   Creating Makefile
> 
>   **********************************************************************
>   ***                                                                ***
>   ***   OpenSSL has been successfully configured                     ***
>   ***                                                                ***
>   ***   If you encounter a problem while building, please open an    ***
>   ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
>   ***   and include the output from the following command:           ***
>   ***                                                                ***
>   ***       perl configdata.pm --dump                                ***
>   ***                                                                ***
>   ***   (If you are new to OpenSSL, you might want to consult the    ***
>   ***   'Troubleshooting' section in the INSTALL file first)         ***
>   ***                                                                ***
>   **********************************************************************
>   running "gmake" "depend"
> 
>   --- stderr
>   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pvmadm/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:488:39
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-deny v0.12.2`, intermediate artifacts can be found at `/tmp/cargo-installqvnEQ5`

OS: FreeBSD-13.1-RELEASE-p1 amd64
rustup 1.25.1 (bb60b1e89 2022-07-12)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
cargo 1.63.0 (fd9c4297c 2022-07-01)
toolchain: stable-x86_64-unknown-freebsd (default)

I'm sorry if this issue has been asked before, I hope you can help me. Thanks

Btw, I've used openssl library before for my other rust project, and it passes just fine (Actix + Openssl)

**Comment by Jake-Shadle** [comment]
That's probably because it's not building from source. If you look at the code that paniced it's trying to run a binary and failing because it can't be found, and the last log line is `running "gmake" "depend"` so I'll assume you don't have gmake installed.

**Comment by JacobsonLantern** [comment]
> That's probably because it's not building from source. If you look at the code that paniced it's trying to run a binary and failing because it can't be found, and the last log line is `running "gmake" "depend"` so I'll assume you don't have gmake installed.

Ah, OK, I've installed gmake and it now works. Thank you.
