### ISSUE TITLE
Whitdrawn advisories are taken into account

### ISSUE THREAD

**Issue by michalfita** [EmbarkStudios/cargo-deny#457]
**Describe the bug**
Withdrawn advisories are shown for dependencies. Refer to: https://github.com/rustsec/advisory-db/issues/1427

**To Reproduce**
1. Use `dirs 4.0` crate in your project
2. Use `cargo deny` (version 0.9.1)
3. Observe the warning about  https://rustsec.org/advisories/RUSTSEC-2020-0053

**Expected behavior**
No warning about withdrawn advisory.

**Screenshots**
![image](https://user-images.githubusercontent.com/4925040/192552530-8b2c71a3-706b-454d-a37f-b4d2e907032b.png)
![image](https://user-images.githubusercontent.com/4925040/192552724-1068cea6-d7f9-4bb5-b70a-169f556b240f.png)

Sorry, if this is already fixed. I cannot at the moment bump up it.

**Comment by Jake-Shadle** [comment]
This issue is due to using a severely outdated cargo-deny and doesn't exist in at least the latest version.
