### ISSUE TITLE
GPL-3.0-only WITH Classpath-exception-2.0 should not count as copyleft or should be made into separate group

### ISSUE THREAD

**Issue by vorot93** [EmbarkStudios/cargo-deny#470]
This license is essentially [LGPL for statically-linked languages](https://opensource.stackexchange.com/a/11619), so it does not infect revdeps.

**Comment by Jake-Shadle** [comment]
I'd rather avoid special casing niche cases like this, and skew towards being conservative, especially when it comes to copyleft that many projects/orgs are allergic to. It's easy enough for a project to opt into that specific license + exception if they want to allow it but deny other copyleft licenses.
