### ISSUE TITLE
Concurrently cloning advisories database fails

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#479]
I'm setting up CI infrastructure running on our own hardware. After installing `cargo deny`, we immediately run it. Because multiple jobs might be running in parallel, it's possible for `cargo deny` to be invoked on different workspaces concurrently. In this case, it seems to fail:

```
2022-11-08 08:52:08 [ERROR] failed to fetch advisory database https://github.com/RustSec/advisory-db: failed to create locked file '/Users/djc/.cargo/advisory-dbs/github.com-2f857891b7f43c59/.git/config.lock': File exists; class=Os (2); code=Locked (-14)
```

It would be great if the API was robust to being invoked from different processes concurrently.

**To Reproduce**
Run `cargo deny check` twice, concurrently, on a machine that doesn't have the advisories database checked out yet.

**Expected behavior**
I'd expect the second process to try to wait for a file lock, ensuring that the database is there.

**Device:**
 - OS: macOS

**Comment by djc** [comment]
@Jake-Shadle thanks for fixing this! Is there some place I can track the next release?

**Comment by Jake-Shadle** [comment]
I'm writing the CHANGELOG right now.

**Comment by djc** [comment]
Awesome!
