### ISSUE TITLE
Treat (`unmatched-skip`) warnings as errors

### ISSUE THREAD

**Issue by MarijnS95** [EmbarkStudios/cargo-deny#480]
**Is your feature request related to a problem? Please describe.**

Whenever we remove a great deal of (transitive) crates, or upgrade our crate dependencies, there's a chance some (possibly duplicate) crate disappears while being specified in `deny.toml`. `cargo-deny` currently emits a useful warning for that such as `warning[license-exception-not-encountered]: license exception was not encountered` or `warning[unmatched-skip]: skipped crate 'xxx = y.y.y' was not encountered`. However, there's currently no way make `cargo-deny` fail in our CI to complain about this overspecification, as we can now finally drop some `skip`/`exception` from our `deny.toml`.

**Describe the solution you'd like**
Treating these warnings as errors, so that our CI fails until the now-unused `skip` declaration has been removed.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Jake-Shadle** [comment]
Use `-D, --deny <lint_names>` https://embarkstudios.github.io/cargo-deny/cli/check.html#-d---deny-deny

**Comment by MarijnS95** [comment]
@Jake-Shadle Ah perfect, thanks! Looks like `-D warnings` catches all warnings, that's amazing!

Didn't know it was a config option on `check` rather than on `cargo deny` (just like how `--workspace` has to be passed before `check`, since it's a subcommand).
