### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by cemoktra** [EmbarkStudios/cargo-deny#483]
**Is your feature request related to a problem? Please describe.**
In CI i would like to react differently on advisories and the other categories. Cause advisories are caused by external parties and a solution might not be available immediately, so this should not stop the pipeline but cause a warning.

**Describe the solution you'd like**
Flag based exit codes could help here. e.g.
- advisories 0x0001
- bans 0x0010
- licenses 0x0100
- sources 0x1000

When combined with OR i could decompose if one category has occured using AND.

**Describe alternatives you've considered**
The alternative currently is running deny twice with different categories, while allowing one to fail. But t should be possible to handle this with one run.

**Comment by ahollmann** [comment]
Exit codes are restricted. You have a range of 0 to 255.

```
EXIT STATUS         [top](https://man7.org/linux/man-pages/man1/exit.1p.html#top_of_page)
       The exit status shall be n, if specified, except that the
       behavior is unspecified if n is not an unsigned decimal integer
       or is greater than 255. Otherwise, the value shall be the exit
       value of the last command executed, or zero if no command was
       executed. When exit is executed in a trap action, the last
       command is considered to be the command that executed immediately
       preceding the trap action.
  ```
