### ISSUE TITLE
Local path dependencies trigger advisory warnings for crates of the same name

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#486]
**Describe the bug**
In opentelemetry we have an example crate called http, which is sitting at version 0.1.0. It recently started triggering the advisory check for RUSTSEC-2019-0033 and RUSTSEC-2019-0034 even though it is a completely different crate (just sharing the same name).

**To Reproduce**
1. Create example crate with same name/version as a crate that has a vulnerability

**Expected behavior**
Would expect to get no warnings/errors in this case.

**Screenshots**
<img width="828" alt="Screenshot 2022-11-28 at 10 07 43" src="https://user-images.githubusercontent.com/158471/204237694-0883931f-364b-4a74-8521-712a41ce81d9.png">

**Comment by Jake-Shadle** [comment]
Duplicate of #446
