### ISSUE TITLE
Only ban multiple versions of user-facing dependencies

### ISSUE THREAD

**Issue by epage** [EmbarkStudios/cargo-deny#497]
**Is your feature request related to a problem? Please describe.**
It can be hard to avoid multiple-versions.  In particular for dev-dependencies as they tend to sprawl out more than normal/build dependencies (e.g. criterion) yet they are a lower priority.  Not many people will care if `clap` has duplicate depednencies for local development but they will care when depending on clap.

**Describe the solution you'd like**
Allow configuring `multiple-versions = "deny"` to only deny when there are multiple within normal/build dependencies

**Describe alternatives you've considered**
- #350 

**Additional context**

Granted, this won't help with `is-terminal` as a normal dependency since it pulls in two different versions of `windows-sys`.

**Comment by jaskij** [comment]
Edge case: there are some crates, like [`build-info`](https://crates.io/crates/build-info) which, afaik, need to have the same version as both dependencies and dev-dependencies.
