### ISSUE TITLE
Allow clarifying unlicensed crates as deliberately unlicensed (previously possible in 0.2)

### ISSUE THREAD

**Issue by iliana** [EmbarkStudios/cargo-deny#50]
**Is your feature request related to a problem? Please describe.**
I am working on a project where I've not identified the license I want to use yet, but I still want to use `licenses.unlicensed = "deny"` to deny unlicensed and unclarified dependencies. Listing a license in either Cargo.toml or deny.toml would be inaccurate if I'm planning on keeping the project history.

**Describe the solution you'd like**
Maybe `Clarification` could have `unlicensed: Option<true>` or the like.

```toml
[[licenses.clarify]]
name = "my-neat-project"
unlicensed = true
```

**Describe alternatives you've considered**
We're currently locking to cargo-deny 0.2 to keep this functionality as part of the `skip` key.

**Comment by Jake-Shadle** [comment]
I could see adding this feature, or maybe even a specific setting for ignoring the root level crate(s).

**Comment by iliana** [comment]
I’d definitely prefer the top-level “unlicensed top level crates” lint argument, that’s a good approach.

**Comment by Jake-Shadle** [comment]
@iliana Oh no, I didn't see offer to implement this! I was thinking of something like `ignore-workspace` or the like which is just a boolean that defaults to `false`. If it's `true` the license check would then just skip any package in this list https://docs.rs/cargo_metadata/0.9.1/cargo_metadata/struct.Metadata.html#structfield.workspace_members (but would probably still emit a Severity::Help that was skipped).
