### ISSUE TITLE
Allow license identifiers not in SPDX (previously possible in 0.2)

### ISSUE THREAD

**Issue by iliana** [EmbarkStudios/cargo-deny#51]
**Is your feature request related to a problem? Please describe.**
As a possible workaround to #50 I thought that it might still be possible to use custom license identifiers (such as `Project-Pending`), but this fails to parse in either Cargo.toml's `license` field or in `licenses.clarify.expression`.

**Describe the solution you'd like**
I'd like to be able to use custom identifiers that aren't part of SPDX if they're syntactically correct.

**Describe alternatives you've considered**
I can write a valid SPDX license but that would be inaccurate (and SPDX doesn't have a "Proprietary" or "Unknown" identifier).

**Comment by Jake-Shadle** [comment]
SPDX allows licenses outside its list by prefixing them with `LicenseRef-` which is supported by cargo-deny. Please reopen if you run into issues with that approach.
