### ISSUE TITLE
README uses SVG images for examples, and this has poor accessibility properties

### ISSUE THREAD

**Issue by jamesyoungman** [EmbarkStudios/cargo-deny#518]
**Describe the bug**
The use of SVG images to display example outputs makes it impossible to cut-and-paste from them to show people why they should use cargo-deny.   It also, I would expect, makes this file hard to read by people who use screen readers.  

**To Reproduce**
1. Visit https://github.com/EmbarkStudios/cargo-deny
2. Look at the example output (scroll down if necessary)
3. Try to copy the example output to your computer's clipboard
4. Fail

**Expected behavior**
Copy example text output to the clipboard as if it were actually text.

**Screenshots**
Yes, these are the problem.

**Device:**
All devices.

**Additional context**
I tried to use the documentation to explain to someone how their Linux distribution might be able to make use of cargo-deny out of the box.  But, I wasn't easily able to do this because I couldn't incorporate the example output in my email.

**Comment by repi** [comment]
could possibly do embedded html for the output in the README that retains the full styling of the terminal output, GitHub does support rendering that. though not sure if there is any good converters for that and would still be work, but is a possible path.

**Comment by Jake-Shadle** [comment]
The problem is that Github doesn't support custom CSS which is what is needed to get the correct colors/styles for the elements in the output, and inline style/color markup is stripped from raw HTML embedded in github markdown. unfortunately.
