### ISSUE TITLE
Correct way to specify that the crate is closed-source/proprietary.

### ISSUE THREAD

**Issue by vidhanio** [EmbarkStudios/cargo-deny#526]
Is there a way to make `cargo-deny` understand my crate is proprietary?

**Comment by ojob** [comment]
Hello @vidhanio,
I’m interested by the way you answered your need, either as defining your project as proprietary, or by changing the expected crate license.

**Comment by ojob** [comment]
OK, found it, may be useful to others:

- in `Cargo.toml`, set `publish` to `false`;
- in `deny.toml`, set `licences.private.ignore` to true.
