### ISSUE TITLE
Section [metadata] seems to no longer be produced by nightly cargo

### ISSUE THREAD

**Issue by dbartussek** [EmbarkStudios/cargo-deny#56]
**Describe the bug**
It seems the nightly compiler no longer puts the hash into a metadata section, but instead in the package list at the "checksum" key. This breaks `cargo deny check ban`.

**To Reproduce**
1. Initialize a new project
2. Add any dependency
3. Compile with nightly
4. Initialize and run `cargo deny check ban`
5. An error message "unable to find metadata section in Cargo.lock".

**Expected behavior**
The ban checker should probably fall back on the "checksum" field if the "metadata" section cannot be found.

**Comment by Jake-Shadle** [comment]
Ahh interesting, I was aware this change was coming, luckily I am doing a separate change that I can fold a fix for this into, thanks for the report!
