### ISSUE TITLE
[FR] Add check for precompiled code

### ISSUE THREAD

**Issue by werdahias** [EmbarkStudios/cargo-deny#560]
Given the recent drama I was wondering if it was sensible to add a check for precompiled code in crates. This would be a nice feature, especially for distro maintainers of rust crates as we can't allow such code in the repos (for obvious reasons).
CC @sdroege @decathorpe

**Comment by Jake-Shadle** [comment]
This was added in 0.14.2 https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html#the-executables-field-optional, but only for crates that can execute code at compile time (proc macros or build scripts).

**Comment by werdahias** [comment]
awesome, thanks.
