### ISSUE TITLE
"Unable to find metadata section" for crates with no dependencies

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#57]
Not a high priority bug but ran into this error for a small test crate that had no dependencies:

`2019-12-14 18:18:08 [ERROR] unable to find metadata section in Cargo.lock`

And yes that is technically correct as the crate had no `[dependencies]` section and as such `Cargo.lock` was very empty:

```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "test-crate"
version = "0.1.0"
```

Logically one could argue cargo-deny should ideally not fail for this case though because there isn't anything to deny. And could be nice to handle that gracefully if cargo deny starts getting used more widely and one uses it from the beginning when creating new crates

**Comment by Jake-Shadle** [comment]
Closing in favor of #56 as it boils down to the same issue.
