### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#6]
We want to publish this properly on crates.io so this tool can be simply installed by CI and users with just "cargo install cargo-deny". 

For this to be possible we can't depend on git dependencies so need to use the `askalono` and `license-exprs` also from crates.io. Hopefully they will merge in our PRs and publish new versions with it, alternatively we could try and find some workaround of using the latest published versions of them.

**Comment by Jake-Shadle** [comment]
I've replaced license-exprs with our own [spdx crate](https://crates.io/crates/spdx). Will either get a PR into askalono, or just use the vanilla crate for now so we can publish a version tomorrow.

**Comment by Jake-Shadle** [comment]
Resolved in #7
