### ISSUE TITLE
Bug: unable to allow intel/ittapi

### ISSUE THREAD

**Issue by dignifiedquire** [EmbarkStudios/cargo-deny#654]
### Describe the bug

I am allowing `BSD 3 Clause` licenses in my project, but I have been unable to build a configuration that clarifies the license for  https://github.com/intel/ittapi/ in a way that `cargo deny` accepts

### To reproduce

Add https://github.com/intel/ittapi/ to the project and run cargo deny 

### cargo-deny version

0.14.20

### What OS were you running cargo-deny on?

MacOS

**Comment by Jake-Shadle** [comment]
ittapi and ittapi-sys clearly state their license in the package manifest https://github.com/intel/ittapi/blob/e20cd6099cb9c5afee0a285781c5cc1d32412f3e/rust/ittapi/Cargo.toml#L10 so I'm not sure why a clarification is desired?

**Comment by dignifiedquire** [comment]
because cargo deny rejects it, even though I allowe Bsd

**Comment by Jake-Shadle** [comment]
Can you please show the exact error?

**Comment by dignifiedquire** [comment]
```
❯ cargo deny check
warning[accepted]: license requirements satisfied
  ┌─ registry+https://github.com/rust-lang/crates.io-index#ittapi@0.4.0:4:12
  │
4 │ license = "GPL-2.0-only OR BSD-3-Clause"
  │            ---------------------------- license expression retrieved via Cargo.toml `license`
  │
  = ittapi v0.4.0
    └── wasmtime v19.0.2
        ├── iroh-fog v0.1.0
        ├── wasi-common v19.0.2
        │   └── <source crate> v0.1.0 (*)
        ├── wasmtime-wasi v19.0.2
        │   └── <source crate> v0.1.0 (*)
        └── wiggle v19.0.2
            ├── wasi-common v19.0.2 (*)
            └── wasmtime-wasi v19.0.2 (*)
```

**Comment by Jake-Shadle** [comment]
That's not an error, it's telling you that the license requirements were satisfied. The reason it is a warning is because you have either `copyleft = 'warn'` or `default = 'warn'` in your config.

**Comment by Jake-Shadle** [comment]
They are enabled by default, use `version = 2` to opt-in to the future breaking change that removes copyleft/default. https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html#the-version-field-optional

**Comment by dignifiedquire** [comment]
I see, thanks for the clarifications!
