### ISSUE TITLE
Allow to deny multiple-versions except for a list of crates

### ISSUE THREAD

**Issue by glandium** [EmbarkStudios/cargo-deny#660]
While
```
[bans]
multiple-versions = "deny"
```
is very much desirable, it is hard to fulfill completely. The typical example right now would be `syn`, where many crates are still using version 1.0.

On the other hand, while there is a documented way to deny multiple-versions of a specific crate, there doesn't seem to be the opposite : denying them all except a given crate.

**Comment by Jake-Shadle** [comment]
https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html#the-skip-field-optional

**Comment by glandium** [comment]
May I suggest an adjustment to the doc to use the word "multiple", like everything else related to the feature? (likewise for the skip-tree feature).

**Comment by glandium** [comment]
Actually the expression "duplicated versions" seems out of place. It should be either "duplicated crates" or "multiple versions".
