### ISSUE TITLE
Add a way to turn `warning[unused-wrapper]` into hard error 

### ISSUE THREAD

**Issue by stormshield-gt** [EmbarkStudios/cargo-deny#665]
**Is your feature request related to a problem? Please describe.**

Since https://github.com/EmbarkStudios/cargo-deny/issues/405 we have a way to detect unused deny `wrappers` which is great. However, this detection only emits warning and don't fail the process when doing `cargo deny check ban`, so it's easy to ignore it in CI.

**Describe the solution you'd like**

It would be great if it we could have the possibility to turn those into hard error. Like the "warning as error" of clippy

**Describe alternatives you've considered**

I could hack a bash script that detects if something was output to stderr and failed in that the case.

```sh
cargo deny check bans 2> /tmp/stderr.log
[ -s /tmp/foo.stderr ] &&  exit 1
```
But I don't think it's a reliable solution

**Comment by Jake-Shadle** [comment]
You can use `-D` just as with cargo clippy to deny specific lints, so using `cargo deny check -D unused-wrapper bans` or `cargo deny check -D all bans` could be used in CI.

**Comment by Jake-Shadle** [comment]
Sorry I misremembered, it's `-D warnings|allowed`.
