### ISSUE TITLE
Bug: unused-workspace-dependencies false positives for any git dependency

### ISSUE THREAD

**Issue by jaskij** [EmbarkStudios/cargo-deny#680]
### Describe the bug

For all my git dependencies, even if they are used under `dependencies` in multiple crates in the workspace, `unused-workspace-dependencies`

### To reproduce

1. workspace
2. git dependency in the workspace
3. a number of crates in the workspace
4. those crates inheriting the workspace dependency
5. cargo deny check

### cargo-deny version

0.15.0

### What OS were you running cargo-deny on?

Linux

**Comment by Jake-Shadle** [comment]
I'll need a repro, git dependencies are tested for, but maybe there is something I missed with source matching.

**Comment by jaskij** [comment]
@Jake-Shadle here: https://github.com/jaskij/workspace-deps-repro

**Comment by Jake-Shadle** [comment]
cargo-deny never looks at source code.

**Comment by jaskij** [comment]
One thing I have noticed, which may or may not matter: some workspaces, but neither mine nor `serde`'s, have a top-level package.

**Comment by Jake-Shadle** [comment]
Thanks for the report and repro, fixed in 0.15.1

**Comment by jaskij** [comment]
Thanks for the quick fix.

Also, since I don't think I said this earlier, thanks for the feature!
