### ISSUE TITLE
workspace-duplicates is oversensitive for intra-workspace path-only dependencies

### ISSUE THREAD

**Issue by adam-azarchs** [EmbarkStudios/cargo-deny#682]
**Is your feature request related to a problem? Please describe.**
We have a monorepo with a large number of crates in the workspace.  We use workspace dependencies for external dependencies, so we really like the `workspace-duplicates` warning, but it's a bit pedantic and arguably not even desirable when it complains about `path` dependencies between different crates in the workspace.

**Describe the solution you'd like**

Do not trigger `workspace-duplicates` if all of the following are true:
1. The dependency is specified _only_ by `path` (as opposed to `path` + version or git target. This necessarily means the referencing crate cannot be published to a registry)
2. The `path` is to another crate in the same workspace.
3. The target crate is private (`publish = false`).

In that situation, it is unlikely that the crate would ever be referred to by anything other than `path`, so adding an entry in the workspace-level `Cargo.toml` is kind of pointless.

**Describe alternatives you've considered**

Adding a configuration option for `workspace-duplicates` to ignore `path`-only dependencies.  This would simplify the  analysis above, as only the first criteria would need to be evaluated.

**Comment by Jake-Shadle** [comment]
Why would it be pointless? That would mean that every dependency declaration would need to use the full relative path making it tedious to move/rename. But I'll add an option.

**Comment by adam-azarchs** [comment]
At least in our workspace, the crate directories are all direct descendants of the workspace directory, so the warnings end up looking like
```
warning[workspace-duplicate]: crate foo = 0.1.0 is used 6 times in the workspace, and there was no shared workspace dependency for it
   ┌─ /.../xxx/Cargo.toml:80:1
   │
80 │ foo = { path = "../foo" }
   │ ────────────────
   │
   ┌─ /.../xxx/Cargo.toml:61:1
   │
61 │ foo = { path = "../foo" }
   │ ────────────────
   │
   ┌─ /.../xxx/Cargo.toml:35:1
   │
35 │ foo = { path = "../foo" }
   │ ────────────────
   │
   ┌─ /.../xxx/Cargo.toml:19:1
   │
19 │ foo= { path = "../foo" }
   │ ────────────────
   │
   ┌─ /.../xxx/Cargo.toml:41:1
   │
41 │ foo = { path = "../foo" }
   │ ────────────────
   │
   ┌─ /.../xxx/Cargo.toml:39:1
   │
39 │ foo = { path = "../foo" }
```
Except multiply that by a couple of dozen values of `foo`.  `workspace = true` wouldn't really be any more concise or maintainable, and certainly less immediately obvious to a reader that the dependency is repository-local.  Adding a couple of dozen additional lines to the workspace `Cargo.toml` would in fact seem to be _less_ maintainable.

Sure, "maybe don't put dozens of crates as sibling directories without any kind of organizing hierarchy" would have been good advice to give several years ago when this workspace was first set up, but here we are.
