### ISSUE TITLE
Bug: Documentation is too strict with "one or more" when 0 values are accepted as well

### ISSUE THREAD

**Issue by Marcono1234** [EmbarkStudios/cargo-deny#689]
### Describe the bug

At multiple places the documentation and the comments in `deny.template.toml` say "one or more" / "1 or more". However, it looks like in many cases 0 values are allowed as well, and even the `deny.template.toml` has cases where it says "one or more" but then below has a TOML array with 0 values, for example:
https://github.com/EmbarkStudios/cargo-deny/blob/aaab4c5c31dce9692bf740872bcacc35c7491550/deny.template.toml#L133-L138

Expected behavior:
- If really "one or more" values are required, it would be good if `deny.template.toml` then followed that, and for example arrays with 0 values are commented out;
and maybe if cargo-deny would fail if 0 values are provided (but this would be backward incompatible)
- Or better: If 0 values are allowed, the wording of the documentation should be adjusted to not sound like at least 1 value is required

### To reproduce

_none_

### cargo-deny version

0.16.0

### What OS were you running cargo-deny on?

None

**Comment by Jake-Shadle** [comment]
Commented out values in the template are to show examples, people blindly copy the template, having actual values would be confusing if they were actually used.

**Comment by Marcono1234** [comment]
I was not suggesting to use un-commented example values. Sorry for the misunderstanding. What I mean is that (for the example above) it should be either:
- The array is completely commented out:
    ```toml
    # One or more private registries ...
    # registries = [ 
    #     "https://sekretz.com/registry 
    # ]
    ```
- It does not say "one or more"
    ```toml
    # Private registries ...
    registries = [ 
        # "https://sekretz.com/registry 
    ]
    ```

The "one or more" sounds like it _must be at least one_, whereas for most or all arrays 0 seems to be allowed as well.

**Comment by Jake-Shadle** [comment]
The template in most cases shows the default values for each key, the default for the private registries is an empty array, the comment is for those who want to actually change the array, if you don't use the array (IMO) it should be deleted as an empty array means nothing happens and just takes up space. Honestly often forget the template even exists, maybe the easiest thing to do is just comment everything and just have hyperlinks to the documentation for each field so there is no/little drift between the template and the actual current configuration.
