### ISSUE TITLE
Bug: pre-commit fails on pr checks

### ISSUE THREAD

**Issue by gacallea** [EmbarkStudios/cargo-deny#693]
### Describe the bug

pre-commit runs fine locally but it fails on pr checks

### To reproduce

1. install hook per docs https://github.com/EmbarkStudios/cargo-deny?tab=readme-ov-file#pre-commit-hook
2. create a pr (e.g: https://github.com/gacallea/freesound-credits/pull/36)
3. it fails like so:

<img width="812" alt="Screenshot 2024-08-11 at 11 19 45 AM" src="https://github.com/user-attachments/assets/e771965a-32a0-40fa-a1f8-522273b3a2aa">

### cargo-deny version

cargo-deny 0.16.1

### What OS were you running cargo-deny on?

GitHub PR

**Comment by Jake-Shadle** [comment]
I mean, it looks like it is building cargo-deny from source? I assume on a not very good machine, as even on my local machine it can take up to 38 seconds for a clean build with `--release`. I'm not sure why you would want to compile cargo-deny from source in your own CI when you could just use the [github action](https://github.com/EmbarkStudios/cargo-deny-action), but I'll accept a PR if there is a fix that can be made to the hook or something, but I have no idea how pre-commit works/is supposed to work as it was an external contribution.

**Comment by gacallea** [comment]
I am not deciding to compile anything. This is not even in my `.github/worflows`

This is inherited by simply using the pre-commit hook. Not sure if it is a pre-commit or your config default to compile from scratch. https://github.com/gacallea/freesound-credits/blob/39b83ebd36057d13603ed009643de3857eb5d923/.pre-commit-config.yaml

**Comment by gacallea** [comment]
ps: I just realized I do use the action tho https://github.com/gacallea/freesound-credits/blob/39b83ebd36057d13603ed009643de3857eb5d923/.github/workflows/cargo-deny.yml. -- they seem unrelated? pre-commit is handy but I wish I could exclude it from the PR runs since I have the action?

**Comment by Jake-Shadle** [comment]
Yah, I don't know how pre-commit works but I would hope it could be made to not run in CI as I would think the point would be that it was already run before pushing. Either way, I'll close this unless there is a PR that could be made to not compile from source and just use the binaries available from release, otherwise I don't think there is anything that can be done from this repo.

**Comment by gacallea** [comment]
I see. How to other pre-commits I have not compile from source or fail then? It seems very specific to your pre-commit? Just trying to wrap my head around it.

**Comment by gacallea** [comment]
could this be related? https://pre-commit.com/#rust

**Comment by Jake-Shadle** [comment]
It sounds like rust is always compiled from source, and if they do caching I don't know what level it is on, so I don't think there is a way to fix this in the repo. Maybe there is a way to increase a timeout somewhere or something.

**Comment by gacallea** [comment]
thanks for the discussion and clarifications, I appreciate :) May file an issue with pre-commit at some point. For now I am still learning this all and finding a setup I like for both local and github checks and all. I may resort to actions/workflows all the way and only use pre-commit locally if I manage to implement all the hooks I need.
