### ISSUE TITLE
Ignore advisories or bans for dependencies of a particular crate

### ISSUE THREAD

**Issue by eric-seppanen** [EmbarkStudios/cargo-deny#716]
I help maintain a large workspace with thousands of dependencies, and run `cargo deny check [advisories|bans]` in CI regularly. Unfortunately, there are some old tools in the workspace that don't receive much maintenance as they are not production tools. When advisories come along, they sometimes can't be resolved without significant work, and being old and out of date (and non-production, non-critical tools) there isn't much appetite for spending time on them.

For the time being, I regularly add `ignore` entries to the `[advisories]` when new advisories come along. This is unsatisfying, as it also ignores the advisory for the code I do care about, potentially allowing a bad dependency to "jump the gap" into the production code.

Similarly, I have tried to ban dependencies that are undesirable for other reasons (e.g. non-additive features that cause odd behavior, or just local preference for a competing crate), but if the crate I want to ban is used transitively in some old tools, that prevents me from adding the ban at all.

**Describe the solution you'd like**

I would like to be able to name an "ignore-me-and-my-dependencies" crate (ideally either a local workspace crate, or a dependency crate) and have advisories or bans be ignored, for dependency graph edges that traverse the "ignore-me-and-my-dependencies" crate. Ideally, I could name any number of crates that will be ignored this way.

This would be really easy if I could write
```plaintext
[excluded]
# Ignore all issues on these crates or their dependencies
crates = [
    "ignore-me",
    "old-tool",
    "old-vendored-crate",
]
```
and have this "excluded" list be applied to advisories and bans.

**Describe alternatives you've considered**
Alternatively, if I could add more fine-grained `ignore` directives, I could imagine being able to live with something like:
```plaintext
[advisories]
ignore = [
    { advisory = "RUSTSEC-0000-0000", except-parent = "old-crate-ignore-me" }
]
```
Or perhaps
```plaintext
[advisories]
ignore = [
    # ignored globally
    "RUSTSEC-0000-0000",
]

[advisories.crate-override]
crate = "old-crate-ignore-me"
ignore = [
    # ignored for this crate and its dependencies
    "RUSTSEC-0001-0001",
]
```

Or for bans:
```plaintext
# The "derivative" crate is unmaintained. Use "derive_more" or "derive-where" instead.
[[bans.deny]]
name = "unwanted"
except-parent = "old-crate-ignore-me"
```

These are a bit more tedious, and the syntax differences between advisories and bans add some friction, but could be made to work.

Another solution might be for us to split up our giant workspace into "production code" and "old nonproduction tools", but that's also a lot of work, and since those two categories are somewhat fluid, would make it more difficult to bring an old tool back to life and reactivate advisory checks.

**Comment by Jake-Shadle** [comment]
https://embarkstudios.github.io/cargo-deny/checks/cfg.html#the-exclude-field-optional

**Comment by eric-seppanen** [comment]
Thank you!
