### ISSUE TITLE
Warn/error if duplicate is allowed, but unnecessary

### ISSUE THREAD

**Issue by sagudev** [EmbarkStudios/cargo-deny#725]
**Is your feature request related to a problem? Please describe.**
We want to replace servo's python lints with cargo-deny, but this is only thing that is missing.

**Describe the solution you'd like**
Detect when a duplicate versions are allowed, but not present. This is useful to keep the list clean.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
Issue in servo: https://github.com/servo/servo/issues/34393
related code in servo: https://github.com/servo/servo/blob/d65a2e97970cbc3900c7f62e1c51776710623887/python/tidy/tidy.py#L375

**Comment by Jake-Shadle** [comment]
FWIW, though I fixed this bug, personally I always use [exact version specifiers](https://github.com/EmbarkStudios/cargo-deny/blob/0c8cb9e89ff31ca8c696851d2329c1c983439caa/deny.toml#L34), as most of the time, skips are temporary when crate used transitively has done a non-patch release and it takes time for all dependencies to use the newer version, so when they all have the skip will no longer match the older version, _and_ it will give an error if another version is somehow used in the graph during that time, unlike using just the crate name, which will match all versions.
