### ISSUE TITLE
Unused dependency check

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#74]
[cargo-udeps](https://github.com/est31/cargo-udeps) is a handy tool to check that all declared dependencies are actually used in a crate, would be a useful check to add.

**Comment by repi** [comment]
think we can close this older issue? as we don't have a path towards it.

we do actively use @bnjbvr 's [cargo-machete](https://github.com/bnjbvr/cargo-machete) in our larger projects, and [cargo-udeps](https://github.com/est31/cargo-udeps) is indeed also an option.

would be great with a fully automated flow that has no false positives or manual fix ups though, but that would probably be another standalone tool or future Cargo feature.

**Comment by Jake-Shadle** [comment]
Yah, forgot this was here.
