### ISSUE TITLE
`advisories.db-path` is not expanded and and directory `~` is created

### ISSUE THREAD

**Issue by oblique** [EmbarkStudios/cargo-deny#96]
**Describe the bug**

`advisories.db-path` is not expanded and and directory `~` is created in project's directory.

**To Reproduce**

```
cargo new project
cd project
cargo deny init
cargo deny check
ls
```

**Expected behavior**

`~/.cargo/advisory-db` to be expanded to `/home/user/.cargo/advisory-db`.

**Comment by Jake-Shadle** [comment]
Oops, we don't expand this ourselves which is why this isn't working.
