### ISSUE TITLE
Default deny.toml contains "~", but shell variables aren't expanded

### ISSUE THREAD

**Issue by Michael-F-Bryan** [EmbarkStudios/cargo-deny#98]
The default `deny.toml` file contains [`db-path = "~/.cargo/advisory-db"`](https://github.com/EmbarkStudios/cargo-deny/blob/2ac5e1d13c3807b1d1f9b5c77d4a6011abf7754b/resources/template.toml#L31), but because `~` isn't expanded to `/home/michael/` (or wherever your `$HOME` is) running `cargo deny check` afterwards will create a folder literally called `~` in the current directory.

# Steps to Reproduce

```console
$ cargo deny --version
cargo-deny 0.5.2
$ cargo new cargo-deny-repro
$ cd cargo-deny-repro
$ cargo deny init
$ ls
Cargo.toml  deny.toml  src
$ rg db-path --context 3
deny.toml
10-# https://github.com/EmbarkStudios/cargo-deny#the-advisories-section
11-[advisories]
12-# The path where the advisory database is cloned/fetched into
13:db-path = "~/.cargo/advisory-db"
14-# The url of the advisory database to use
15-db-url = "https://github.com/rustsec/advisory-db"
16-# The lint level for security vulnerabilities
$ cargo deny check
...
$ ls
Cargo.lock  Cargo.toml  deny.toml  src  ~
```

(as a bonus, try to delete this new `~` without accidentally blowing away your entire home directory :rofl:)

# Possible Resolutions

There are a couple ways this could be solved.

1. As a special case, do `deny_toml_text.replace("~", std::env::home_dir())` before parsing the `deny.toml` (doesn't account for `$VARIABLES` and escaping)
2. Use a crate like [shellexpand](https://docs.rs/shellexpand/1.1.1/shellexpand/) to do proper shell expansion (adds a dependency, and may accidentally leak sensitive information?)

**Comment by Jake-Shadle** [comment]
Duplicate of #96
